### ISSUE TITLE
Extending existing tag

### ISSUE THREAD

**Issue by kelvinss** [x-tag/core#149]
Can I extend an existing tag using `x-tag`? Like this:

```js
var xButton = document.registerElement('x-button', {
  prototype: Object.create(HTMLButtonElement.prototype),
  extends: 'button'
});
```
```html
<button is="x-button"></button>
```

**Comment by csuwildcat** [comment]
You don't even need to worry about the complexity of constructing your own prototype with `Object.create()`, just use the regular X-Tag API format for defining Custom Element, and include the `extends` property with the string of the element you are extending:

```javascript
var xButton = xtag.register('x-button', {
  extends: 'button',
  lifecycle: {},
  events: {},
  methods: {},
  // etc.
});
```

Then use it as you correctly cited: `<button is="x-button"></button>`

**Comment by kelvinss** [comment]
Oh, thanks! It's working, but totally missing in the docs. How can I edit the docs?

**Comment by kelvinss** [comment]
I have another question. Is this:
```js
var xElement = xtag.register('x-elem', {
    methods: {
        some_constant: 'value'
    }
});
```
a valid way to store some "class" level constants, without having `this.xtag.attr = value` every time on `created` lifecycle callback?

**Comment by csuwildcat** [comment]
You can edit the docs by simply adding new content to the GitHub pages org
site here: https://github.com/x-tag/x-tag.github.io/blob/master/index.html

There are a couple ways to add constant property values:

1)

xtag.register('x-elem', {
    prototype: {
        some_constant: {
            value: 'value'
       }
    }
});

2) Or you can wrap you definition in a closure and reference a variable in
the closure.
On Apr 28, 2016 7:01 AM, "Kelvin Steiner" <notifications@github.com> wrote:

I have another question. Is this:

var xElement = xtag.register('x-elem', {
    methods: {
        some_constant: 'value'
    }
});

a valid way to store some "class" level constants, without having
this.xtag.attr
= value every time on created lifecycle callback?

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/x-tag/core/issues/149#issuecomment-215432819>

**Comment by csuwildcat** [comment]
This is now working in master - please open another ticket if you experience any further issues :)
