### ISSUE TITLE
How to create custom sub-elements the right way

### ISSUE THREAD

**Issue by obihill** [x-tag/core#167]
Nice work on this project. Looking to use it soon and I wanted to ask a quick question.

So I know x-tag enables you create custom elements that appear in HTML like this:

```
<x-my-custom-element>my content</x-my-custom-element>
```

However, what if I wanted to create multiple custom sub-elements, like this:

```
<x-my-custom-element>
    <x-my-custom-element-child>
        <x-my-custom-element-grandchild></x-my-custom-element-grandchild>
    </x-my-custom-element-child>
</x-my-custom-element>
```

Is the right way to simply call `register()` three times with `x-my-custom-element`, `x-my-custom-element-child`, and `x-my-custom-element-grandchild`?

**Comment by jpecor-pmi** [comment]
Yes, you'll need to use `xtag.register()` for any custom elements.  Rather than adding a GitHub issue for questions like this, I recommend using the [x-tag community chat](http://x-tag.github.io/community) or ask at [StackOverflow.com](http://stackoverflow.com/questions/tagged/x-tag) under the "x-tag" tag.

**Comment by obihill** [comment]
Thanks. Also, my apologies for using the wrong channel. I've posted the question on [StackOverflow](http://stackoverflow.com/questions/41394425/the-right-way-to-create-custom-sub-elements-with-x-tag) for posterity.
